#index:
#    path: /
#    controller: App\Controller\DefaultController::index
log_details:
    path:  /log/details/{username}
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\LogController::details
